version: '3'

services:
  my_site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - './nginx-sites/:/etc/nginx/conf.d/'
      - './site/:/usr/share/nginx/html/'
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - './db/:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
    - MARIADB_DATABASE=project_desafio12
    - MARIADB_ROOT_USER=root
    - MARIADB_USER=useradm
    - MARIADB_PASSWORD=PasswordQ4312
    - MYSQL_ROOT_PASSWORD=PasswordQ4312
    - MYSQL_ALLOW_EMPTY_PASSWORD=PasswordQ4312
    - MYSQL_RANDOM_ROOT_PASSWORD=PasswordQ4312