apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-plain
  namespace: argocd
spec:
  destination:
    namespace: myapp-namespace-plain
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - ApplyOutOfSyncOnly=true
